-- Migration: Add attribution index and support Bench Boss/Captain Heart field mappings
-- Date: 2025-11-24
-- Description: 
--   Adds index on attribution field for efficient filtering by character (Bench Boss/Captain Heart).
--   This migration supports the new M-Gen character-based generation system where content
--   is generated by Bench Boss or Captain Heart personas and stored with character attribution.

BEGIN;

-- ========================================================================
-- STEP 1: Add index on attribution field for character filtering
-- ========================================================================

-- Index on attribution for filtering by character (Bench Boss, Captain Heart, etc.)
CREATE INDEX IF NOT EXISTS idx_collection_hockey_motivate_attribution 
  ON public.collection_hockey_motivate(attribution);

-- ========================================================================
-- STEP 2: Update table comment to reflect character-based generation
-- ========================================================================

COMMENT ON COLUMN public.collection_hockey_motivate.attribution IS 
  'Attribution/character information for the motivational quote (e.g., "Bench Boss", "Captain Heart", author name, etc.)';

COMMIT;

-- ========================================================================
-- VERIFICATION QUERIES (uncomment to run manually)
-- ========================================================================

-- Verify index was created
-- SELECT indexname, indexdef 
-- FROM pg_indexes 
-- WHERE schemaname = 'public' 
--   AND tablename = 'collection_hockey_motivate'
--   AND indexname = 'idx_collection_hockey_motivate_attribution';

-- Test query performance with attribution filter
-- EXPLAIN ANALYZE
-- SELECT * FROM public.collection_hockey_motivate 
-- WHERE attribution = 'Bench Boss' 
-- ORDER BY created_at DESC 
-- LIMIT 10;

